"""
FaceFuel — Tongue v4 Fix
========================
Fixes identified from real-world testing:

  Fix 1: Geographic over-triggering
          - 3,525 pseudo-labels generated from simple texture analysis
          - Most are wrong — reduces to ~300 high-confidence only
          - New threshold: requires BOTH high spatial variance AND
            confirmed patchy depapillated areas (L channel variance pattern)

  Fix 2: Thick coating severely under-detected
          - Old LAB threshold (mL>170) was too strict
          - New: uses combined L brightness + B channel + texture
          - Also catches black hairy tongue via dark coating detection

  Fix 3: Fissured under-detected
          - Add directional gradient analysis (fissures = strong vertical edges)
          - Supplement existing CSV labels

  Fix 4: Add black_hairy_tongue as class 11
          - Scraped from web images in existing unlabeled pool
          - Detected via: dark L (<100) + high texture + elongated pattern

  Fix 5: red_tongue false positive suppression
          - Was triggering on yellow/orange tongues
          - Now requires A>150 AND B<145 (pure red, not yellow-red)

Run:
  python tongue_fix_v4.py              ← fix labels + retrain
  python tongue_fix_v4.py --audit      ← just show label stats, no changes
  python tongue_fix_v4.py --fix-only   ← fix labels, skip training
"""

import argparse, json, shutil, csv, cv2, yaml
import numpy as np
from pathlib import Path
from collections import defaultdict

BASE       = Path("tongue_datasets")
MERGED     = BASE / "TONGUE_MERGED"
COMBINED   = BASE / "TONGUE_COMBINED"
LBL_DIR    = MERGED / "labels"
IMG_DIR    = MERGED / "images"
PSEUDO_LBL = MERGED / "pseudo_labels"
PSEUDO_IMG = MERGED / "pseudo_images"
RUN_DIR    = Path("runs/tongue")

# Updated class list — black_hairy_tongue added as class 11
CLASSES = [
    "tongue_body",      # 0
    "fissured",         # 1
    "crenated",         # 2
    "pale_tongue",      # 3
    "red_tongue",       # 4
    "yellow_coating",   # 5
    "white_coating",    # 6
    "thick_coating",    # 7
    "geographic",       # 8
    "smooth_glossy",    # 9
    "tooth_marked",     # 10
    "black_hairy_tongue", # 11 — NEW
]
IMAGE_EXTS = {".jpg",".jpeg",".png"}


# ═══════════════════════════════════════════════════════════════
# AUDIT
# ═══════════════════════════════════════════════════════════════

def audit():
    print("=" * 65)
    print("Tongue Dataset Audit")
    print("=" * 65)
    counts = defaultdict(int)
    total  = 0

    for lbl in list(LBL_DIR.glob("*.txt")) + list(PSEUDO_LBL.glob("*.txt")):
        for line in lbl.read_text(errors="ignore").splitlines():
            parts = line.strip().split()
            if parts and parts[0].isdigit():
                counts[int(parts[0])] += 1
                total += 1

    print(f"\n  {'Class':<22s}  {'Count':>7}  {'% of total':>10}  Status")
    print(f"  {'-'*60}")
    for i, name in enumerate(CLASSES[:11]):
        cnt = counts.get(i, 0)
        pct = cnt/total*100 if total>0 else 0
        flag = ""
        if i==8 and cnt>1000:  flag = " ← ⚠️  OVER-TRIGGERED"
        if i==7 and cnt<200:   flag = " ← ⚠️  UNDER-DETECTED"
        if i==1 and cnt<200:   flag = " ← ⚠️  UNDER-DETECTED"
        print(f"  {name:<22s}  {cnt:>7,}  {pct:>9.1f}%{flag}")
    print(f"\n  Total annotations: {total:,}")


# ═══════════════════════════════════════════════════════════════
# FIX 1: Purge bad geographic pseudo-labels
# ═══════════════════════════════════════════════════════════════

def purge_geographic():
    """
    Remove geographic pseudo-labels that were generated by simple
    texture analysis. Keep only ones that co-occur with strong
    supporting evidence (tongue_body present + spatial variance
    confirmed on the actual image).
    """
    print("\n" + "="*60)
    print("Fix 1 — Purging bad geographic pseudo-labels")
    print("="*60)

    removed = 0
    kept    = 0

    for lbl_path in PSEUDO_LBL.glob("*.txt"):
        lines = lbl_path.read_text(errors="ignore").strip().splitlines()
        has_geo = any(l.strip().startswith("8 ") for l in lines)
        if not has_geo:
            continue

        # Check if geographic is the ONLY meaningful label (sign of false positive)
        other_cls = [l.strip().split()[0] for l in lines
                     if l.strip() and not l.strip().startswith("8 ")
                     and not l.strip().startswith("0 ")]

        # Load image and verify with stricter spatial variance check
        img_path = PSEUDO_IMG / (lbl_path.stem.lstrip("p_") + ".jpg")
        if not img_path.exists():
            # Try other extensions
            for ext in IMAGE_EXTS:
                candidate = PSEUDO_IMG / (lbl_path.stem + ext)
                if candidate.exists():
                    img_path = candidate
                    break

        verified = False
        if img_path.exists():
            img = cv2.imread(str(img_path))
            if img is not None:
                verified = verify_geographic(img)

        if not verified:
            # Remove geographic (class 8) from this label file
            new_lines = [l for l in lines if not l.strip().startswith("8 ")]
            if new_lines:
                lbl_path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
            else:
                lbl_path.write_text("", encoding="utf-8")
            removed += 1
        else:
            kept += 1

    print(f"  Removed geographic from : {removed:,} files")
    print(f"  Kept verified geographic : {kept:,} files")
    return removed


def verify_geographic(img_bgr: np.ndarray) -> bool:
    """
    Strict geographic tongue verification.
    True geographic tongue has:
    1. Very high inter-region L variance (patchy depapillation)
    2. Clear boundary between smooth patches and rough papillae
    3. NOT simply high texture or high brightness
    """
    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY).astype(np.float32)
    lab  = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2LAB).astype(np.float32)
    L    = lab[:,:,0]
    h, w = gray.shape

    # Focus on central tongue region
    y1,y2 = int(h*0.15), int(h*0.85)
    x1,x2 = int(w*0.15), int(w*0.85)
    Lr = L[y1:y2, x1:x2]
    if Lr.size < 100: return False

    # Divide into 4x4 grid and measure L mean per cell
    grid_means = []
    rows, cols = Lr.shape
    for gy in range(4):
        for gx in range(4):
            r1 = int(rows*gy/4); r2 = int(rows*(gy+1)/4)
            c1 = int(cols*gx/4); c2 = int(cols*(gx+1)/4)
            cell = Lr[r1:r2, c1:c2]
            if cell.size > 0:
                grid_means.append(float(np.mean(cell)))

    if not grid_means: return False
    spatial_std = float(np.std(grid_means))

    # Geographic requires VERY high spatial std (>18)
    # AND some cells must be significantly lighter (depapillated patches)
    # AND some cells must be darker (remaining papillae)
    arr = np.array(grid_means)
    has_bright_patch = (arr > np.mean(arr) + 15).any()
    has_dark_patch   = (arr < np.mean(arr) - 15).any()

    return spatial_std > 18 and has_bright_patch and has_dark_patch


# ═══════════════════════════════════════════════════════════════
# FIX 2: Better thick_coating detection
# ═══════════════════════════════════════════════════════════════

def improve_thick_coating():
    """
    Re-run coating detection with better thresholds.
    Thick coating = high L brightness + high B (yellow) OR low L (dark coating).
    Also detects black hairy tongue as class 11.
    """
    print("\n" + "="*60)
    print("Fix 2+4 — Improving thick_coating + black_hairy_tongue detection")
    print("="*60)

    # Process ALL images including main labeled set
    target_dirs = [IMG_DIR, PSEUDO_IMG,
                   BASE / "preprocessedcropped",
                   BASE / "Tongue_color_v20"]
    all_imgs = []
    for d in target_dirs:
        if d.exists():
            for ext in IMAGE_EXTS:
                all_imgs.extend(d.rglob(f"*{ext}"))

    added_thick = 0
    added_black = 0
    updated     = 0

    for img_path in all_imgs:
        img = cv2.imread(str(img_path))
        if img is None: continue

        thick_score, black_score = analyze_coating(img)

        if thick_score < 0.35 and black_score < 0.40:
            continue

        # Determine label file location
        stem = img_path.stem
        lbl_path = LBL_DIR / f"{stem}.txt"
        if not lbl_path.exists():
            lbl_path = PSEUDO_LBL / f"{stem}.txt"

        existing = lbl_path.read_text(errors="ignore").strip() \
                   if lbl_path.exists() else ""

        new_lines = []
        if thick_score >= 0.35:
            line = "7 0.500000 0.500000 0.950000 0.950000"
            if line not in existing:
                new_lines.append(line); added_thick += 1

        if black_score >= 0.40:
            line = "11 0.500000 0.500000 0.950000 0.950000"
            if line not in existing:
                new_lines.append(line); added_black += 1

        if new_lines:
            dst_img = PSEUDO_IMG / img_path.name
            if not dst_img.exists():
                shutil.copy2(img_path, dst_img)
            lbl_out = PSEUDO_LBL / f"{dst_img.stem}.txt"
            with open(lbl_out, "a", encoding="utf-8") as f:
                f.write(("\n" if existing else "") + "\n".join(new_lines) + "\n")
            updated += 1

    print(f"  thick_coating labels added   : {added_thick:,}")
    print(f"  black_hairy_tongue labels added: {added_black:,}")
    print(f"  Files updated                : {updated:,}")


def analyze_coating(img_bgr: np.ndarray) -> tuple:
    """
    Returns (thick_coating_score, black_hairy_tongue_score).
    Uses raw image (pre-normalization) for reliable absolute thresholds.
    """
    lab  = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2LAB).astype(np.float32)
    L, A, B = lab[:,:,0], lab[:,:,1], lab[:,:,2]
    h, w = L.shape

    # Central tongue region
    y1,y2 = int(h*0.15), int(h*0.85)
    x1,x2 = int(w*0.15), int(w*0.85)
    Lc,Ac,Bc = L[y1:y2,x1:x2], A[y1:y2,x1:x2], B[y1:y2,x1:x2]
    if Lc.size < 100: return 0.0, 0.0

    mL = float(np.mean(Lc))
    mA = float(np.mean(Ac))
    mB = float(np.mean(Bc))
    std_L = float(np.std(Lc))

    # ── Thick coating (white/yellow) ──────────────────────────
    # White coating: high L (>165), neutral A/B
    white_coat = mL > 165 and abs(mA-128) < 12 and abs(mB-128) < 12
    # Yellow coating as thick: high L + high B
    yellow_thick = mL > 155 and mB > 148 and mA < 145
    # General thick: very high L (>170)
    very_bright  = mL > 170

    thick_score = 0.0
    if white_coat:   thick_score = max(thick_score, float(np.clip((mL-165)/30,0,1)))
    if yellow_thick: thick_score = max(thick_score, float(np.clip((mB-148)/25,0,1)))
    if very_bright:  thick_score = max(thick_score, float(np.clip((mL-170)/25,0,1)))

    # ── Black hairy tongue ────────────────────────────────────
    # Very dark L (<105) + brownish/neutral A + high texture
    sx    = cv2.Sobel(Lc, cv2.CV_32F, 0, 1, ksize=3)  # vertical = hair texture
    sy    = cv2.Sobel(Lc, cv2.CV_32F, 1, 0, ksize=3)
    vert_grad = float(np.mean(np.abs(sx)))
    horiz_grad = float(np.mean(np.abs(sy)))
    elongated = vert_grad > horiz_grad * 1.3   # more vertical than horizontal

    black_score = 0.0
    if mL < 105 and elongated:
        black_score = float(np.clip((105-mL)/40,0,1)) * 0.8 + \
                      float(np.clip(vert_grad/15,0,1)) * 0.2

    # Dark but not black — brownish/hairy
    if 105 <= mL < 130 and std_L < 20 and elongated:
        black_score = max(black_score, float(np.clip((130-mL)/25,0,0.7)))

    return thick_score, black_score


# ═══════════════════════════════════════════════════════════════
# FIX 3: Better fissured detection
# ═══════════════════════════════════════════════════════════════

def improve_fissured():
    """
    Supplement fissured detection using directional gradient analysis.
    Fissures = strong vertical/diagonal dark lines running length of tongue.
    """
    print("\n" + "="*60)
    print("Fix 3 — Improving fissured detection")
    print("="*60)

    target_dirs = [IMG_DIR, PSEUDO_IMG,
                   BASE / "preprocessedcropped"]
    all_imgs = []
    for d in target_dirs:
        if d.exists():
            for ext in IMAGE_EXTS:
                all_imgs.extend(d.rglob(f"*{ext}"))

    added = 0

    for img_path in all_imgs:
        img = cv2.imread(str(img_path))
        if img is None: continue

        score = detect_fissures(img)
        if score < 0.65: continue

        stem     = img_path.stem
        lbl_path = LBL_DIR / f"{stem}.txt"
        if not lbl_path.exists():
            lbl_path = PSEUDO_LBL / f"{stem}.txt"

        existing = lbl_path.read_text(errors="ignore").strip() \
                   if lbl_path.exists() else ""

        # Don't add if already has fissured label
        if "1 " in existing: continue

        line = f"1 0.500000 0.500000 0.950000 0.950000"
        dst_img = PSEUDO_IMG / img_path.name
        if not dst_img.exists():
            shutil.copy2(img_path, dst_img)
        lbl_out = PSEUDO_LBL / f"{dst_img.stem}.txt"
        with open(lbl_out, "a", encoding="utf-8") as f:
            f.write(("\n" if existing else "") + line + "\n")
        added += 1

    print(f"  Fissured labels added: {added:,}")


def detect_fissures(img_bgr: np.ndarray) -> float:
    """
    Detect tongue fissures using directional Sobel analysis.
    Fissures are strong, elongated dark lines running along tongue length.
    """
    gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY).astype(np.float32)
    h, w = gray.shape

    y1,y2 = int(h*0.10), int(h*0.90)
    x1,x2 = int(w*0.20), int(w*0.80)
    region = gray[y1:y2, x1:x2]
    if region.size < 100: return 0.0

    # Strong vertical gradient = fissure (dark line going top-to-bottom)
    sx     = cv2.Sobel(region, cv2.CV_32F, 1, 0, ksize=3)
    sy     = cv2.Sobel(region, cv2.CV_32F, 0, 1, ksize=3)

    # Fissures: vertical edges (sx large) that are consistent (not noise)
    # Use percentile to capture significant edges only
    sx_abs = np.abs(sx)
    p90_x  = float(np.percentile(sx_abs, 90))
    p90_y  = float(np.percentile(np.abs(sy), 90))

    # Strong vertical lines (fissures) have high p90 horizontal gradient
    if p90_x < 15: return 0.0  # raised from 8 — must be strong edges

    # Ratio: fissured tongue has much stronger horizontal gradient than vertical
    ratio = p90_x / (p90_y + 1e-6)

    # Also check for linear dark structures (Hough-like: count strong vertical pixels)
    strong_v = (sx_abs > p90_x * 0.8).astype(np.float32)
    col_sums = strong_v.sum(axis=0)
    # Fissure = tall column of strong pixels
    long_lines = (col_sums > region.shape[0] * 0.25).sum()
    line_density = long_lines / max(region.shape[1], 1)

    # Both ratio AND line_density must be strong — prevents noise triggering
    if ratio < 2.0 or line_density < 0.12:
        return 0.0
    score = float(np.clip((ratio - 2.0) / 2.0, 0, 0.5) +
                  np.clip((line_density - 0.12) / 0.15, 0, 0.5))
    return min(score, 1.0)


# ═══════════════════════════════════════════════════════════════
# FIX 5: Suppress red_tongue false positives on yellow tongues
# ═══════════════════════════════════════════════════════════════

def fix_red_tongue_labels():
    """
    Remove red_tongue pseudo-labels from images that are actually
    yellow/orange tongues (high B channel = yellow, not red).
    """
    print("\n" + "="*60)
    print("Fix 5 — Suppressing red_tongue false positives")
    print("="*60)

    fixed = 0
    for lbl_path in PSEUDO_LBL.glob("*.txt"):
        lines = lbl_path.read_text(errors="ignore").strip().splitlines()
        has_red = any(l.strip().startswith("4 ") for l in lines)
        if not has_red: continue

        # Load image and check if it's actually yellow
        img_path = None
        for ext in IMAGE_EXTS:
            p = PSEUDO_IMG / (lbl_path.stem + ext)
            if p.exists(): img_path = p; break

        if not img_path: continue
        img = cv2.imread(str(img_path))
        if img is None: continue

        lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB).astype(np.float32)
        h,w = lab.shape[:2]
        y1,y2 = int(h*0.15),int(h*0.85)
        x1,x2 = int(w*0.15),int(w*0.85)
        Ac = lab[y1:y2,x1:x2,1]; Bc = lab[y1:y2,x1:x2,2]
        mA = float(np.mean(Ac)); mB = float(np.mean(Bc))

        # Remove red_tongue if B channel indicates yellow/orange (B>145)
        # OR if A channel is not actually high enough for real red
        is_yellow = mB > 145
        is_not_red = mA < 148

        if is_yellow or is_not_red:
            new_lines = [l for l in lines if not l.strip().startswith("4 ")]
            lbl_path.write_text(("\n".join(new_lines) + "\n") if new_lines else "",
                                 encoding="utf-8")
            fixed += 1

    print(f"  Removed false red_tongue labels: {fixed:,}")


# ═══════════════════════════════════════════════════════════════
# REBUILD + TRAIN
# ═══════════════════════════════════════════════════════════════

def rebuild_combined():
    print("\n" + "="*60)
    print("Rebuilding TONGUE_COMBINED v4...")
    print("="*60)
    import random; random.seed(42)

    if COMBINED.exists(): shutil.rmtree(COMBINED)

    for split in ["train","val"]:
        for sub in ["images","labels"]:
            (COMBINED/split/sub).mkdir(parents=True, exist_ok=True)

    # Collect all pairs
    all_pairs = []
    for img in IMG_DIR.glob("*.*"):
        if img.suffix.lower() not in IMAGE_EXTS: continue
        lbl = LBL_DIR / f"{img.stem}.txt"
        if lbl.exists(): all_pairs.append((img, lbl, False))

    if PSEUDO_IMG.exists():
        for img in PSEUDO_IMG.glob("*.*"):
            if img.suffix.lower() not in IMAGE_EXTS: continue
            lbl = PSEUDO_LBL / f"{img.stem}.txt"
            if lbl.exists(): all_pairs.append((img, lbl, True))

    random.shuffle(all_pairs)
    sp = int(len(all_pairs)*0.8)
    train_p, val_p = all_pairs[:sp], all_pairs[sp:]

    class_counts = defaultdict(int)

    def copy_split(pairs, split):
        for img, lbl, pseudo in pairs:
            pfx = "p_" if pseudo else ""
            di  = COMBINED/split/"images"/(pfx+img.name)
            dl  = COMBINED/split/"labels"/(pfx+img.stem+".txt")
            if not di.exists(): shutil.copy2(img, di)
            if not dl.exists():
                # Update class count to 12
                shutil.copy2(lbl, dl)
            for line in lbl.read_text(errors="ignore").splitlines():
                parts = line.strip().split()
                if parts and parts[0].isdigit():
                    class_counts[int(parts[0])] += 1

    copy_split(train_p, "train")
    copy_split(val_p,   "val")

    yaml_path = COMBINED/"data.yaml"
    with open(yaml_path,"w") as f:
        yaml.dump({
            "train": str((COMBINED/"train"/"images").resolve()),
            "val":   str((COMBINED/"val"/"images").resolve()),
            "nc":    len(CLASSES),
            "names": CLASSES,
        }, f, default_flow_style=False, allow_unicode=True)

    print(f"  Train: {len(train_p):,}  Val: {len(val_p):,}")
    print(f"  Class distribution v4:")
    for i,name in enumerate(CLASSES):
        cnt = class_counts.get(i,0)
        bar = "█"*min(30,cnt//20)
        flag = ""
        if i==8 and cnt>800:  flag=" ← still high"
        if i==8 and cnt<500:  flag=" ← ✅ fixed"
        if i==11 and cnt>0:   flag=" ← ✅ new class"
        print(f"    {i:2d}  {name:<22s}  {cnt:5d}  {bar}{flag}")

    return yaml_path


def train_v4(yaml_path: Path, epochs: int = 80):
    import torch
    from ultralytics import YOLO

    device = "0" if torch.cuda.is_available() else "cpu"
    candidates = (list(Path(".").rglob("tongue_v3_improved/weights/best.pt")) +
                  list(Path(".").rglob("tongue_v2_retrain/weights/best.pt")))
    weights = str(candidates[0]) if candidates else "yolov8m.pt"
    print(f"\n  Starting from: {weights}")
    print(f"\n{'='*60}")
    print(f"Training Tongue v4  ({epochs} epochs, 12 classes)")
    print(f"{'='*60}")

    model = YOLO(weights)
    results = model.train(
        data          = str(yaml_path),
        epochs        = epochs,
        imgsz         = 640,
        batch         = 16,
        workers       = 0,
        device        = device,
        project       = str(RUN_DIR),
        name          = "tongue_v4_fixed",
        patience      = 30,
        lr0           = 8e-5,         # Low LR — fine-tuning from v3
        lrf           = 0.01,
        warmup_epochs = 3,
        box           = 7.5,
        cls           = 3.5,          # Higher cls — 12 unbalanced classes
        hsv_h         = 0.025,        # Slightly more hue variation
        hsv_s         = 0.6,
        hsv_v         = 0.4,
        fliplr        = 0.5,
        flipud        = 0.0,
        degrees       = 12,
        scale         = 0.3,
        mosaic        = 0.85,
        mixup         = 0.2,          # Mixup helps rare classes
        copy_paste    = 0.1,
        save          = True,
        exist_ok      = True,
        verbose       = True,
    )
    best = next(Path(".").rglob("tongue_v4_fixed/weights/best.pt"), None)
    map50 = results.results_dict.get("metrics/mAP50(B)", "N/A")
    print(f"\n  ✅ v4 training complete")
    print(f"  Best: {best}")
    print(f"  mAP@0.5: {map50}")
    print(f"\n  Next: re-extract features and retrain severity MLP")
    print(f"    python tongue_features.py")
    print(f"    python tongue_severity.py --train")


# ═══════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--audit",      action="store_true")
    parser.add_argument("--fix-only",   action="store_true")
    parser.add_argument("--train-only", action="store_true")
    parser.add_argument("--epochs",     type=int, default=80)
    args = parser.parse_args()

    audit()   # always show stats first

    if args.audit:
        exit(0)

    if not args.train_only:
        removed = purge_geographic()
        improve_thick_coating()
        improve_fissured()
        fix_red_tongue_labels()
        print(f"\n  {'='*60}")
        print(f"  All fixes applied. Re-running audit...")
        audit()

    yaml_path = rebuild_combined()

    if not args.fix_only:
        train_v4(yaml_path, args.epochs)
